"""second Migration

Revision ID: 59d6ea1185b8
Revises: f3e0af32a7b6
Create Date: 2021-09-20 20:53:32.796315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d6ea1185b8'
down_revision = 'f3e0af32a7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_Secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_Secure')
    # ### end Alembic commands ###
